# permissions for end users to view encryptedsecrets.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: encryptedsecret-viewer-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: encryted-secrets
    app.kubernetes.io/part-of: encryted-secrets
    app.kubernetes.io/managed-by: kustomize
  name: encryptedsecret-viewer-role
rules:
- apiGroups:
  - secrets.opensecrecy.org
  resources:
  - encryptedsecrets
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - secrets.opensecrecy.org
  resources:
  - encryptedsecrets/status
  verbs:
  - get
