apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "encrpyted-secrets.fullname" . }}-manager-role
  labels:
  {{- include "encrpyted-secrets.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.opensecrecy.org
  resources:
  - encryptedsecrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - secrets.opensecrecy.org
  resources:
  - encryptedsecrets/finalizers
  verbs:
  - update
- apiGroups:
  - secrets.opensecrecy.org
  resources:
  - encryptedsecrets/status
  verbs:
  - get
  - patch
  - update
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "encrpyted-secrets.fullname" . }}-manager-rolebinding
  labels:
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: encryted-secrets
    app.kubernetes.io/part-of: encryted-secrets
  {{- include "encrpyted-secrets.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: '{{ include "encrpyted-secrets.fullname" . }}-manager-role'
subjects:
- kind: ServiceAccount
  name: '{{ include "encrpyted-secrets.fullname" . }}-controller-manager'
  namespace: '{{ .Release.Namespace }}'